# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjectTest2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 5.4'

  # Pods for ProjectTest2

  target 'ProjectTest2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjectTest2UITests' do
    # Pods for testing
  end

end
